name: platform
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/simpleitk
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - openssl=3.3.1
  - pip=24.2
  - python=3.10.14
  - setuptools=72.1.0
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - apscheduler==3.10.4
    - audioread==3.0.1
    - baidu-aip==4.16.13
    - bidict==0.23.1
    - blinker==1.8.2
    - certifi==2024.7.4
    - cffi==1.17.0
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.2.1
    - cycler==0.12.1
    - decorator==5.1.1
    - dnspython==2.6.1
    - eventlet==0.36.1
    - faiss-cpu==1.7.4
    - flask==3.0.3
    - flask-cors==4.0.1
    - flask-socketio==5.3.6
    - fonttools==4.53.1
    - greenlet==3.0.3
    - h11==0.14.0
    - idna==3.7
    - imageio==2.35.1
    - itsdangerous==2.2.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - librosa==0.10.2.post1
    - llvmlite==0.43.0
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - msgpack==1.0.8
    - networkx==3.3
    - nltk==3.9.1
    - numba==0.60.0
    - numpy==1.26.4
    - opencv-python==4.10.0.84
    - packaging==24.1
    - pillow==10.4.0
    - platformdirs==4.2.2
    - pooch==1.8.2
    - pyclipper==1.3.0.post5
    - pycparser==2.22
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-engineio==4.9.1
    - python-socketio==5.11.3
    - pytz==2024.1
    - regex==2024.7.24
    - requests==2.32.3
    - scikit-image==0.24.0
    - scikit-learn==1.5.1
    - scipy==1.14.0
    - shapely==2.0.5
    - simple-websocket==1.0.0
    - six==1.16.0
    - soundfile==0.12.1
    - soxr==0.4.0
    - sqlalchemy==2.0.32
    - threadpoolctl==3.5.0
    - tifffile==2024.8.10
    - torch==1.11.0+cu113
    - torchaudio==0.11.0+cu113
    - torchvision==0.12.0+cu113
    - tqdm==4.66.5
    - trimesh==4.4.6
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - tzlocal==5.2
    - urllib3==2.2.2
    - werkzeug==3.0.3
    - wsproto==1.2.0
